[package]
name = "stripe-rust" # b.c. stripe and stripe-rs were already taken
version = "0.9.0"
description = "API bindings for the Stripe v1 HTTP API"
authors = [
  "Anna Baldwin <abaldwin@developers.wyyerd.com>",
  "Kevin Stenerson <kstenerson@developers.wyyerd.com>"
]
license = "MIT/Apache-2.0"
repository = "https://github.com/wyyerd/stripe-rs"
documentation = "https://docs.rs/stripe-rust"
keywords = ["stripe", "v1", "api"]
categories = ["api-bindings"]
edition = "2018"

[badges]
travis-ci = {repository = "wyyerd/stripe-rs"}

[lib]
name = "stripe"

[features]
default = ["webhooks"]
webhooks = ["hmac", "sha2"]

# TODO: Deprecate `async` after we can use Generic Associated Types
# (see https://github.com/rust-lang/rust/issues/44265)
async = []

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
futures = "0.1.23"
reqwest = "0.9"
serde = "<1.0.118, >=1.0.79" # N.B. we use `serde(other)` which was introduced in `1.0.79`
serde_derive = "<1.0.118, >=1.0.79"
serde_json = "1.0"
serde_qs = "0.5"

# Webhook support
hmac = { version = "0.7", optional = true }
sha2 = { version = "0.8", optional = true }

[[example]]
name = "async_create_charge"
required-features = ["async"]