##
## Version: 0.12.0-alpha.1
##

[[benchmark]]
commit = "915c23ba56d2e67e5fc5f0ec94019176b9795866"
hardware = "MacBook Air (13-inch, 2018)"
features = [] # e.g. async
#time = { ... }
size = { release = "4.9M", stripped = "3.9M", lib = "2.2M" }

[[benchmark]]
commit = "915c23ba56d2e67e5fc5f0ec94019176b9795866"
hardware = "MacBook Air (13-inch, 2018)"
features = ["blocking"]
#time = { ... }
size = { release = "5.1M", stripped = "4.1M", lib = "2.3M" }

[[benchmark]]
commit = "0e78fe46ac2a067e01fa1803b9cc14bdf0dd9f01"
hardware = "MacBook Air (13-inch, 2018)"
features = ["blocking"]
time = { debug = "3m 11s", release = "7m 48s" }
size = { debug = "23M", release = "5.7M", stripped = "4.6M", lib = "1.8M" }

[[benchmark]]
commit = "54d7a1b7adf6ec20a1af665b46bb0f2b356b6f06"
hardware = "MacBook Air (13-inch, 2018)"
features = ["blocking"]
time = { debug = "3m 51s", release = "8m 21s" }
size = { debug = "30.5M", release = "7.9M", stripped = "6.5M", lib = "1.8M" }

[[benchmark]]
commit = "54d7a1b7adf6ec20a1af665b46bb0f2b356b6f06"
hardware = "MacBook Air (13-inch, 2018)"
features = ["full", "blocking"]
time = { debug = "5m 00s", release = "13m 03s" }
size = { debug = "42.3M", release = "11M", stripped = "9M", lib = "3.9M" }
